name = "Approach"
tools_version = "5.9"
default_localization = "en"

# Platforms

[platforms.iOS]
supported = [ "\"17.0\"" ]

# Features

[features.Analysis]
features = [ "Hints", "SolutionsList" ]
services = [ "Solver" ]

[features.App]
features = [ "PlaysList" ]

[features.Hints]
libraries = [ "Dictionary", "SharedModels" ]
dependencies = [ "ComposableArchitecture" ]

[features.PlayDetails]
features = [ "Analysis" ]
repositories = [ "Plays" ]

[features.PlaysList]
features = [ "RecordPlay", "Statistics" ]

[features.RecordPlay]
features = [ "PlayDetails" ]

[features.Statistics]
repositories = [ "Statistics" ]
libraries = [ "Views" ]

[features.SolutionsList]
libraries = [ "SharedModels" ]

# Repositories

[repositories.Plays]

[repositories.Statistics]

# Services

[services.Dictionary]
[services.Dictionary.interface]
libraries = [ "Dictionary" ]

[services.Persistence]
libraries = [ "PersistentModels" ]

[services.Persistence.interface]
libraries = [ "SharedModels" ]
dependencies = [ "GRDB" ]

[services.Solver]
services = [ "Dictionary", "Validator" ]

[services.Solver.interface]
libraries = [ "SharedModels" ]

[services.Validator]

[services.Validator.interface]
libraries = [ "Dictionary", "SharedModels" ]

# Libraries

[libraries.Dictionary]

[libraries.Extensions]

[libraries.PersistentModels]
skip_tests = true
libraries = [ "SharedModels" ]
dependencies = [ "GRDB" ]

[libraries.SharedModels]
libraries = [ "Extensions" ]
[libraries.SharedModels.tests]
libraries = [ "SharedModelsMocks" ]

[libraries.SharedModelsMocks]
skip_tests = true
libraries = [ "SharedModels" ]

[libraries.Views]
skip_tests = true

# Dependencies

[dependencies.ComposableArchitecture]
url = "https://github.com/pointfreeco/swift-composable-architecture.git"
from = "1.10.2"

[dependencies.Dependencies]
url = "https://github.com/pointfreeco/swift-dependencies.git"
from = "1.2.2"

[dependencies.DependenciesMacros]
url = "https://github.com/pointfreeco/swift-dependencies.git"
from = "1.2.2"

[dependencies.GRDB]
url = "https://github.com/groue/GRDB.swift.git"
from = "6.27.0"

# Defaults

[defaults.features]
dependencies = [ "ComposableArchitecture" ]

[defaults.features.tests]
libraries = [ "SharedModelsMocks" ]

[defaults.repositories]
services = [ "Persistence" ]
libraries = [ "PersistentModels" ]

[defaults.repositories.interface]
libraries = [ "SharedModels" ]
dependencies = [ "Dependencies" ]

[defaults.services.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]
